/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.nlt.view;

/**
 *
 * @author Gauri Bhamkar
 */
public class CitiesFrame extends javax.swing.JFrame {

    /**
     * Creates new form CitiesFrame
     */
    public CitiesFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cityTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        stateComboBox1 = new javax.swing.JComboBox<>();
        stateNewButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        submitButton3 = new javax.swing.JButton();
        updateButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        deleteButton1 = new javax.swing.JButton();
        resetButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cityTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(2, 1, 20, 20));

        jPanel2.setLayout(new java.awt.GridLayout(3, 2, 20, 20));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Enter City:");
        jPanel2.add(jLabel1);

        cityTextField2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel2.add(cityTextField2);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Select State:");
        jPanel2.add(jLabel2);

        jPanel6.setLayout(new java.awt.BorderLayout(20, 0));

        stateComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        stateComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateComboBox1ActionPerformed(evt);
            }
        });
        jPanel6.add(stateComboBox1, java.awt.BorderLayout.CENTER);

        stateNewButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        stateNewButton1.setText("New");
        stateNewButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateNewButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(stateNewButton1, java.awt.BorderLayout.EAST);

        jPanel2.add(jPanel6);

        jPanel5.setLayout(new java.awt.GridLayout(1, 2, 20, 20));

        submitButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        submitButton3.setText("Submit");
        submitButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(submitButton3);

        updateButton4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        updateButton4.setText("Update");
        updateButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(updateButton4);

        jPanel2.add(jPanel5);

        jPanel4.setLayout(new java.awt.GridLayout(1, 2, 20, 20));

        deleteButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        deleteButton1.setText("Delete");
        deleteButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(deleteButton1);

        resetButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        resetButton2.setText("Reset");
        resetButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(resetButton2);

        jPanel2.add(jPanel4);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        cityTable1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cityTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(cityTable1);

        jPanel3.add(jScrollPane1);

        jPanel1.add(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitButton3ActionPerformed

    private void deleteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButton1ActionPerformed

    private void stateNewButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateNewButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateNewButton1ActionPerformed

    private void stateComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CitiesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CitiesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CitiesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CitiesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CitiesFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable cityTable1;
    private javax.swing.JTextField cityTextField2;
    private javax.swing.JButton deleteButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton resetButton2;
    public javax.swing.JComboBox<String> stateComboBox1;
    private javax.swing.JButton stateNewButton1;
    private javax.swing.JButton submitButton3;
    private javax.swing.JButton updateButton4;
    // End of variables declaration//GEN-END:variables
}
